# frozen_string_literal: true

source "https://rubygems.org"
gem "cucumber", "7.1"
gem "capybara", "3.33"
gem "selenium-webdriver", "4.1.0"
gem "rspec", "3.10"
gem "faker", "2.14"
gem "cpf_faker", "1.3"
gem "httparty", "0.13.7"
gem "allure-cucumber", "2.15"
gem "recaptcha", "3.3"
gem "devise", "4.8.0"
gem "puppeteer-ruby", "0.32.1"
gem "json", "2.5.0"
